title: k - blog
preserveTaxonomyNames: true
enableRobotsTXT: true
enableEmoji: true
theme: PaperMod
enableGitInfo: true
hasCJKLanguage: true
paginate: 5
copyright: ""

sitemap:
  changefreq: daily
  priority: 0.5
  filename: sitemap.xml
mainsections: ["post"]
menu:
  main:
    - name: Home
      weight: 10
      identifier: home
      url: /
    - name: Archive
      weight: 20
      identifier: archives
      url: /archives/
    - name: Categories
      weight: 30
      identifier: categories
      url: /categories/
    - name: Tags
      weight: 40
      identifier: tags
      url: /tags/
    - name: Journals
      weight: 50
      identifier: journals
      url: /journal/
    - name: English
      weight: 60
      identifier: english
      url: /english
    - name: Fitness
      weight: 70
      identifier: fitness
      url: /fitness
    - name: About
      weight: 80
      identifier: about
      url: /about
    - name: Search
      url: search/
      weight: 90
params:
  defaultTheme: auto
  comments: true
  since: "2022"
  description: "k's blog."
  archivePaginate: 50
  showArchiveCount: false
  dateFormatToUse: "2006-01-02 15:04:05"
  ShowCodeCopyButtons: true
  # 主页格式
  homeInfoParams:
    Title: "k's blog"
    Content: 👋 Welcome to k's blog!
  socialIcons:
    - name: github
      title: View on Github
      url: "https://github.com/Heyxk"
  # artalk评论系统
  artalk:
    cdnJS: "https://cdnjs.cloudflare.com/ajax/libs/artalk/2.8.2/Artalk.js"
    cdnCSS: "https://cdnjs.cloudflare.com/ajax/libs/artalk/2.8.2/Artalk.css"
    server: "http://192.168.2.218:23366"
    site: "k's blog dev"
  # umami统计
  umami:
    cdnJS: ""
    data_website_id: "7caf0230-fad3-461b-a122-d25d1ef5e5f3"
    data_host_url: "http://192.168.2.218:3000"

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
