params:
  # artalk 评论系统
  artalk:
    cdnJS: "https://cdnjs.cloudflare.com/ajax/libs/artalk/2.8.2/Artalk.js"
    cdnCSS: "https://cdnjs.cloudflare.com/ajax/libs/artalk/2.8.2/Artalk.css"
    server: "https://ar.cookbyte.net"
    site: "k's blog"
  # umami 统计
  umami:
    cdnJS: ""
    data_website_id: "dfb1398b-bfb8-4eaa-ac2f-a86adeef48f3"
    data_host_url: "https://um.cookbyte.net"
