name: Generate Site
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive) 获取 submodule 主题
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.121.1" # 可以修改为你使用的 Hugo 版本
          extended: true # 设置是否需要 extended 版本

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_KEY_TO_DEPLOY_BLOG_BY_GITHUB_ACTIONS }} # 另外还支持 github_token 和 deploy_key (https://github.com/peaceiris/actions-gh-pages#readme)
          external_repository: Heyxk/Heyxk.github.io # GitHub Pages 仓库
          publish_dir: ./public
          keep_files: false
          publish_branch: master
          # 如果使用自定义域名，还需要添加下面一行配置
          cname: cookbyte.net
