name: Generate Site
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out source
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive) 获取submodule主题
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest" # 可以修改为你使用的 Hugo 版本
          extended: true # 设置是否需要 extended 版本

      - name: Modify theme-even font
        run: |
          sed -i "s/\$global-serif-font-family: Athelas, STHeiti, Microsoft Yahei, serif \!default;/\$global-serif-font-family: 'PingFang SC', 'Microsoft Yahei', sans-serif \!default;/g" themes/even/assets/sass/_variables.scss
          sed -i "s/\$logo-font-family: 'Chancery', cursive, LiSu, sans-serif \!default;/\$logo-font-family: 'PingFang SC', 'Microsoft YaHei', cursive, LiSu, sans-serif \!default;/g" themes/even/assets/sass/_variables.scss
          sed -i "s/\$theme-color-config: 'Default';/\$theme-color-config: 'Mint Green';/g" themes/even/assets/sass/_variables.scss
          sed -i "/\/\/ Font family: Chancery/,+13d" themes/even/assets/sass/_variables.scss
          rm -r themes/even/static/fonts/chancery

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_TOKEN }} # 另外还支持 github_token 和 personal_token
          external_repository: Heyxk/Heyxk.github.io # GitHub Pages 仓库
          publish_dir: ./public
          keep_files: false
          publish_branch: master
          # 如果使用自定义域名，还需要添加下面一行配置
          # cname: cookbyte.net
